kind: pipeline
name: default

steps:
- name: build
  image: python:3.7-stretch
  commands:
    - pip3 install flask
    - python3 setup.py test

- name: notify
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
      channel: notifications
  when:
    status: [success, failure]

---
kind: secret
name: slack_webhook
get:
  path: cd-slack-webhook
  name: webhook-url

