# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_demo.proto',
  package='demo',
  syntax='proto3',
  serialized_pb=_b('\n\x0fgrpc_demo.proto\x12\x04\x64\x65mo\"M\n\x13\x44oubleNestedMessage\x12\x1a\n\x12\x64oublenestedvalue1\x18\x01 \x01(\t\x12\x1a\n\x12\x64oublenestedvalue2\x18\x02 \x01(\t\"l\n\rNestedMessage\x12\x14\n\x0cnestedvalue1\x18\x01 \x01(\t\x12\x14\n\x0cnestedvalue2\x18\x02 \x01(\t\x12/\n\x0c\x64oublenested\x18\x03 \x01(\x0b\x32\x19.demo.DoubleNestedMessage\"R\n\x0b\x44\x65moMessage\x12\x0e\n\x06value1\x18\x01 \x01(\t\x12\x0e\n\x06value2\x18\x02 \x01(\t\x12#\n\x06nested\x18\x03 \x01(\x0b\x32\x13.demo.NestedMessage\"\x0e\n\x0c\x45mptyMessage2\x94\x02\n\x0b\x44\x65moService\x12\x33\n\x07\x44\x65moRPC\x12\x12.demo.EmptyMessage\x1a\x12.demo.EmptyMessage\"\x00\x12\x43\n\x17\x44\x65moRPCHandledException\x12\x12.demo.EmptyMessage\x1a\x12.demo.EmptyMessage\"\x00\x12\x45\n\x19\x44\x65moRPCUnHandledException\x12\x12.demo.EmptyMessage\x1a\x12.demo.EmptyMessage\"\x00\x12\x44\n\x19\x44\x65moRPCRedactedParameters\x12\x11.demo.DemoMessage\x1a\x12.demo.EmptyMessage\"\x00\x62\x06proto3')
)




_DOUBLENESTEDMESSAGE = _descriptor.Descriptor(
  name='DoubleNestedMessage',
  full_name='demo.DoubleNestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doublenestedvalue1', full_name='demo.DoubleNestedMessage.doublenestedvalue1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doublenestedvalue2', full_name='demo.DoubleNestedMessage.doublenestedvalue2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=102,
)


_NESTEDMESSAGE = _descriptor.Descriptor(
  name='NestedMessage',
  full_name='demo.NestedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nestedvalue1', full_name='demo.NestedMessage.nestedvalue1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nestedvalue2', full_name='demo.NestedMessage.nestedvalue2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='doublenested', full_name='demo.NestedMessage.doublenested', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=212,
)


_DEMOMESSAGE = _descriptor.Descriptor(
  name='DemoMessage',
  full_name='demo.DemoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value1', full_name='demo.DemoMessage.value1', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value2', full_name='demo.DemoMessage.value2', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nested', full_name='demo.DemoMessage.nested', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=214,
  serialized_end=296,
)


_EMPTYMESSAGE = _descriptor.Descriptor(
  name='EmptyMessage',
  full_name='demo.EmptyMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=298,
  serialized_end=312,
)

_NESTEDMESSAGE.fields_by_name['doublenested'].message_type = _DOUBLENESTEDMESSAGE
_DEMOMESSAGE.fields_by_name['nested'].message_type = _NESTEDMESSAGE
DESCRIPTOR.message_types_by_name['DoubleNestedMessage'] = _DOUBLENESTEDMESSAGE
DESCRIPTOR.message_types_by_name['NestedMessage'] = _NESTEDMESSAGE
DESCRIPTOR.message_types_by_name['DemoMessage'] = _DEMOMESSAGE
DESCRIPTOR.message_types_by_name['EmptyMessage'] = _EMPTYMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoubleNestedMessage = _reflection.GeneratedProtocolMessageType('DoubleNestedMessage', (_message.Message,), dict(
  DESCRIPTOR = _DOUBLENESTEDMESSAGE,
  __module__ = 'grpc_demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.DoubleNestedMessage)
  ))
_sym_db.RegisterMessage(DoubleNestedMessage)

NestedMessage = _reflection.GeneratedProtocolMessageType('NestedMessage', (_message.Message,), dict(
  DESCRIPTOR = _NESTEDMESSAGE,
  __module__ = 'grpc_demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.NestedMessage)
  ))
_sym_db.RegisterMessage(NestedMessage)

DemoMessage = _reflection.GeneratedProtocolMessageType('DemoMessage', (_message.Message,), dict(
  DESCRIPTOR = _DEMOMESSAGE,
  __module__ = 'grpc_demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.DemoMessage)
  ))
_sym_db.RegisterMessage(DemoMessage)

EmptyMessage = _reflection.GeneratedProtocolMessageType('EmptyMessage', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYMESSAGE,
  __module__ = 'grpc_demo_pb2'
  # @@protoc_insertion_point(class_scope:demo.EmptyMessage)
  ))
_sym_db.RegisterMessage(EmptyMessage)



_DEMOSERVICE = _descriptor.ServiceDescriptor(
  name='DemoService',
  full_name='demo.DemoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=315,
  serialized_end=591,
  methods=[
  _descriptor.MethodDescriptor(
    name='DemoRPC',
    full_name='demo.DemoService.DemoRPC',
    index=0,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_EMPTYMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DemoRPCHandledException',
    full_name='demo.DemoService.DemoRPCHandledException',
    index=1,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_EMPTYMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DemoRPCUnHandledException',
    full_name='demo.DemoService.DemoRPCUnHandledException',
    index=2,
    containing_service=None,
    input_type=_EMPTYMESSAGE,
    output_type=_EMPTYMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DemoRPCRedactedParameters',
    full_name='demo.DemoService.DemoRPCRedactedParameters',
    index=3,
    containing_service=None,
    input_type=_DEMOMESSAGE,
    output_type=_EMPTYMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMOSERVICE)

DESCRIPTOR.services_by_name['DemoService'] = _DEMOSERVICE

# @@protoc_insertion_point(module_scope)
